### ISSUE TITLE
Add Compliance check: githubOrgMFA

### ISSUE THREAD

**Issue by UlisesGascon** [secure-dashboards/openjs-foundation-dashboard#43]
### How the Check Works

After some research, it seems like `two_factor_requirement_enabled` is the best field that can provide us with the information from the table `github_organizations`, which we populate from the GitHub API.

> When the value of `two_factor_requirement_enabled` is `true`, the organization requires all members, billing managers, and outside collaborators to enable [two-factor authentication](https://docs.github.com/articles/securing-your-account-with-two-factor-authentication-2fa/). [GH API documentation](https://docs.github.com/en/rest/orgs/orgs?apiVersion=2022-11-28#get-an-organization)

**Main logic:**
- If the value is `true`, it is considered as `passed`.
- If the value is `false`, it is considered as `failed`.
- If the value is `NULL`, it is considered as `unknown`.

**Logic Edge Cases (multiple GitHub organizations):**
1. With a single `failed` organization, the global check is considered `failed`.
2. With a single `unknown` organization (without any `failed` ones), the global check is considered `unknown`.
3. Only if all the organizations have `passed`, the global consideration is `passed`.

**Alerts:**
- Trigger alerts only when there are `failed` organizations in the project. Ignore other scenarios.

**Tasks:**
- Same as alerts.

### Pending Tasks
- [x] **1. Define a Good Implementation** 
  - [x] Read the documentation (guidelines, best practices...)
  - [x] Brainstorm how to implement this check (logic, alerts, tasks, validations, edge cases...).
  - [x] Achieve an agreement on the implementation details before starting to work on this.
- [x] **2. Update Check Record**
  - [x] Update the `compliance_checks` row with the following fields: `how_to_url`, `implementation_status`, `implementation_type` and `implementation_details_reference`
  - [x] Check the migration scripts using `npm run db:migrate` and `npm run db:rollback`
  - [x] Update the database schema by running `npm run db:generate-schema`
- [x] **3. Implement the Business Logic**
  - [x] Add the specific validator in `src/checks/validators/index.js`
  - [x] Add the check logic in `src/checks/complianceChecks`
  - [x] Ensure that the check is in scope for the organization (use `isCheckApplicableToProjectCategory`)
  - [x] Ensure that the `severity` value is well calculated (use `getSeverityFromPriorityGroup`)
  - [x] Add the alert row in the `compliance_checks_alerts` table when is needed.
  - [x] Add the task row in the `compliance_checks_tasks` table when is needed.
  - [x] Add the result row in the `compliance_checks_results` table.
- [x] **4. Ensure It Works as Expected**
  - [x] Add new unit tests for the validator check.
  - [x] Add new integration test cases for this check.
  - [x] Verify that all tests are passing.
  - [x] Run the command `check run --name {check_code_name}` and verify the changes in the database. Update the seed script if needed (`npm run db:seed`)
- [x] **5. Update the website**
  - [x] Review the current content it in `https://openjs-security-program-standards.netlify.app/details/{check_code_name}`
  - [x] Create a PR in https://github.com/secure-dashboards/openjs-security-program-standards to include how we calculate this check and include additional information on the mitigation if needed.

**Comment by UlisesGascon** [comment]
After some research seems like `two_factor_requirement_enabled` is the best field that can provide us the information from the table `github_organizations` that we populate from the GitHub API.

> When the value of `two_factor_requirement_enabled` is `true`, the organization requires all members, billing managers, and outside collaborators to enable [two-factor authentication](https://docs.github.com/articles/securing-your-account-with-two-factor-authentication-2fa/). [GH API documentation](https://docs.github.com/en/rest/orgs/orgs?apiVersion=2022-11-28#get-an-organization)

**Logic**

Main logic:
- If the value is `true` then is considered as `passed`
- If the value is `false` then is considered as `failed`
- If the value is `NULL` then is considered as `unknown`

Edge cases (multiple GitHub organizations):
- 1. With a single `failed` organization, the global check is considered `failed`
- 2. With a single `unkown` organization (without `failed` ones), the global check is considered `unknown`
- 3. Only if all the orgs have `passed` the global consideration is `passed`

**Comment by UlisesGascon** [comment]
Both PRs are landed, so this check is considered completed at this stage :partying_face:
